config/routes.rb
Craigsflick::Application.routes.draw do

  get "permissions/authenticate"

  resources :sets

  controller :permissions do
    delete 'logout' => :destroy
    post 'permissions' => :create
  end

  resources :permissions

  root :to => "permissions#index", :as => 'home'

end

app/models/flickr.rb
class Flickr

  def initialize(url)
    @url = url
    FlickRaw.api_key = credentials[:key]
    FlickRaw.shared_secret = credentials[:secret]
  end

  def url
    frob = flickr.auth.getFrob
    FlickRaw.auth_url :frob => frob, :perms => 'read'
  end

  def login(frob)
    begin
      auth = flickr.auth.getToken :frob => frob
      login = flickr.test.login
      {:auth_token => auth.token, :user_id => login.id}
    rescue FlickRaw::FailedResponse
      nil
    end
  end

  def sets(user_id)
    begin
      sets = flickr.photosets.getList(:user_id => user_id)
      sets.map do |set|
        {
            :id => set.id,
            :name => set.title,
            :description => set.description,
            :count => set.photos,
            :primary_url => FlickRaw.url_t(set_normalize(set))
        }
      end
    rescue FlickRaw::FailedResponse
      nil
    end

  end

  def photos(set_id)
    photos = flickr.photosets.getPhotos(:photoset_id => set_id, :extras => "url_m")

    photos.photo.map do |photo|
      {
          :url => photo.url_m,
          :name => photo.title,
          :user => photos.ownername
      }
    end
  end

  def set_normalize(set)
    PhotoFromSet.new(set)
  end


  def credentials
    if Rails.env.development?
      if @url.include? 'fuck'
          #chris
          {:key => '50d9ac23dbe5f2861533ba5d7298857b', :secret => '8f58d0de127827d0'}
        elsif @url.include? 'winning'
          #tim
          {:key => '00df746ec86d858b365921cc8131356c', :secret => '37c0d7244bc8b327'}
      end

    else
      {:key => 'f3283743a59586a7bc3cabe615336034', :secret => '10a545042e3e1b8c'}
    end
  end

end

class PhotoFromSet

  attr_reader :id, :farm, :secret, :server

  def initialize(set)
    @id = set.primary
    @farm = set.farm
    @secret = set.secret
    @server = set.server
  end

end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery
end

app/controllers/permissions_controller.rb
class PermissionsController < ApplicationController

  def authenticate
    flick = Flickr.new(request.url)
    if frob = request[:frob]
      if login = flick.login(frob)
        session[:user_id] = login[:user_id]
        redirect_to sets_url
      else
        redirect_to permissions_url, :notice => "User refused authentication"
      end
    else
      redirect_to permissions_url, :notice => "User refused authentication"
    end
  end

  def index
    if session[:user_id]
      redirect_to(sets_url)
    end
  end

  def create
    flick = Flickr.new(request.url)
    redirect_to flick.url
  end

  def destroy
    if session[:user_id]
      session[:user_id] = nil
    end
    redirect_to permissions_path, :notice => "You have been logged out."
  end

end

app/controllers/sets_controller.rb
class SetsController < ApplicationController
  def index
    flick = Flickr.new(request.url)
    @sets = flick.sets(session[:user_id])

    respond_to do |format|
      format.html do
        if !@sets
          redirect_to permissions_path, :notice => "No Sets Found."
        end
      end
    end
  end

  def show
    flick = Flickr.new(request.url)
    @photos = flick.photos(params[:id])
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/permissions_helper.rb
module PermissionsHelper
end

app/helpers/sets_helper.rb
module SetsHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Craigsflick</title>
  <%= stylesheet_link_tag :all %>
  <%= csrf_meta_tag %>
</head>
<body>
<% if session[:user_id] %>
    <div>
      <%= button_to "Logout", '/permissions/logout/', :method => :delete %>
    </div>
<% end %>
<%= yield %>
</body>
</html>

app/views/permissions/authenticate.html.erb
<h1>Permissions#authenticate</h1>
<p>Find me in app/views/permissions/authenticate.html.erb</p>

app/views/permissions/index.html.erb
<%= notice %><br />
<%= session[:user_id] %>
<%= button_to "Click me to get started.", permissions_path, :method => :post %>

app/views/sets/index.html.erb
<p>You've reached the set page fuck shit piss</p>
<ul>
  <% @sets.each do |set| %>
   <li>
     <%= link_to(image_tag(set[:primary_url], :alt => set[:name]), sets_path+"/#{set[:id]}") %>
   </li>
  <% end %>
</ul>

app/views/sets/show.html.erb
<html>
<body>
<% str='' %>
<% @photos.each do |photo| %>
    <% str+="<a href=\"#{photo[:url]}\" title=\"#{photo[:title]} by #{photo[:user]}, on Flickr\"><img src=\"#{photo[:url]}\" width=\"1024\" height=\"765\" alt=\"Photo inserted by Craigsflick.com\"></a><br />\n\n" %>
<% end %>

<label for="output">Copy the links below to Craigslist</label><br />
<textarea id="output" rows="10" cols="90"><%= str %></textarea><br />

<div id="preview">
  <% @photos.each_with_index do |photo, i| %>
      <% row_class = i%2 == 0 ? "even" : "odd" %>
      <img src="<%= photo[:url] %>" class="<%= row_class %>"alt=""><br/>
  <% end %>
</div>

</body>
</html>